name: CI

on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      -[main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v2
        with:
          test-plan-path: './GoogleJenkins.jmx'
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
         name: jmeter-results
         path: result.jtl
         
 
          
